config/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

from posts.views import class_view, url_view, url_parameter_view, function_view, index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view),
    path('fbv/', function_view),
    path('cbv/', class_view.as_view()),

    path('', index, name='index'),
    path('posts/', include('posts.urls', namespace='posts')),
]

posts/urls.py
from django.urls import path
from .views import post_list_view, post_create_view, post_detail_view, post_update_view, post_delete_view


app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='post-list'),
    path('new/', post_create_view),
    path('<int:id>/', post_detail_view),
    path('<int:id>/edit/', post_update_view),
    path('<int:id>/delete/', post_delete_view),
]

posts/models.py
from statistics import mode
from tabnanny import verbose
from tkinter import CASCADE
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    image = models.ImageField(verbose_name='이미지', null=True, blank=True)
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    view_count = models.IntegerField(verbose_name='조회수', default=0)
    writer = models.ForeignKey(
        to=User, on_delete=models.CASCADE, null=True, blank=True)


class Comment(models.Model):
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    post = models.ForeignKey(to='Post', on_delete=models.CASCADE)
    writer = models.ForeignKey(
        to=User, on_delete=models.CASCADE, null=True, blank=True)

supports/models.py
from email.mime import image
from statistics import mode
from tabnanny import verbose
from tkinter import CASCADE
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Faq(models.Model):

    CATEGORY_CHOICES = [
        ('일반', '일반'),
        ('계정', '계정'),
        ('기타', '기타'),
    ]

    question = models.TextField(verbose_name='질문')
    category = models.TextField(choices=CATEGORY_CHOICES, verbose_name='카테고리')
    answer = models.TextField(verbose_name='답변')
    writer = models.ForeignKey(
        to=User, on_delete=models.CASCADE, null=True, blank=True, auto_created=True, related_name='faq_creater')

    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    last_modified_at = models.DateTimeField(
        verbose_name='마지막 수정일', auto_now=True)
    last_modified_writter = models.ForeignKey(
        to=User, on_delete=models.CASCADE, related_name='faq_modifier', null=True, blank=True)


class Inquiry(models.Model):
    title = models.TextField(verbose_name='제목')
    email = models.EmailField(verbose_name='이메일')  # 체크박스로 수신유무결정
    phone_number = models.CharField(
        verbose_name='답변수신 폰번호', max_length=12)  # 체크박스로 수신유무결정
    content = models.TextField("문의 내용")
    image = models.ImageField(verbose_name='이미지', null=True, blank=True)
    writter = models.ForeignKey(
        to=User, on_delete=models.CASCADE, null=True, blank=True, auto_created=True, related_name='inq_creater')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    last_modified_at = models.DateTimeField(
        verbose_name='마지막 수정일', auto_now=True)
    last_modified_writter = models.ForeignKey(
        to=User, on_delete=models.CASCADE, null=True, blank=True, related_name='inq_modifier')


class Answer(models.Model):
    ref_inquiry = models.ForeignKey(to="Inquiry", on_delete=models.CASCADE)
    content = models.TextField(verbose_name='답변내용')
    writter = models.ForeignKey(
        to=User, on_delete=models.CASCADE, null=True, blank=True, auto_created=True, related_name='ans_creater')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    last_modified_at = models.DateTimeField(
        verbose_name='마지막 수정일', auto_now=True)
    last_modified_writter = models.ForeignKey(
        to=User, on_delete=models.CASCADE, null=True, blank=True, related_name='ans_modifier')

posts/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView
from .models import Post


def index(reqeust):
    return render(reqeust, 'index.html')


def post_list_view(reqeust):
    return render(reqeust, 'posts/post_list.html')


def post_detail_view(reqeust, id):
    return render(reqeust, 'posts/post_detail.html')


def post_create_view(reqeust):
    return render(reqeust, 'posts/post_form.html')


def post_update_view(reqeust, id):
    return render(reqeust, 'posts/post_form.html')


def post_delete_view(reqeust, id):
    return render(reqeust, 'posts/post_confirm_delete.html')


def url_view(request):
    print('url_view()')
    data = {'code': '001', 'msg': 'OK'}
    return JsonResponse(data)
    # return HttpResponse('<h1>url_view</h1>')


# 뷰에서 데이터를 받는법
# 1.path variable지정 2.query parameter stream ?, key:value형태 3.form으로 입력
# url 패턴으로 변수를 정의해 놓은경우는 parameter로 추가해서 받을수 있고
# query로는 request.GET으로 받을수있어
def url_parameter_view(request, username):
    print('url_parameter_view()')
    print(f'username: {username}')
    print(f'request.GET: {request.GET}')
    return HttpResponse(username)


def function_view(request):
    print(f'request.method: {request.method}')
    if request.method == 'GET':
        print(f'request.GET: {request.GET}')
    elif request.method == 'POST':
        print(f'request.POST: {request.POST}')

    return render(request, 'view.html')


class class_view(ListView):
    model = Post
    ordering = ['-id']
    # template_name = 'cbv_view.html'

# def function_list_view(request):
#     object_list = Post.objects.all().order_by('-id')
#     return render(request, 'cbv_view.html', {'object_list': object_list})

supports/views.py
from django.shortcuts import render

# Create your views here.

posts/templates/cbv_view.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% for object in object_list %}
    <p>{{ object }}</p>
    {% endfor %}
</body>

</html>

posts/templates/view.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <a href="/fbv/">새로고침</a><br>

    <form action="" method="GET">
        <input type="text" name="var">
        <input type="submit" value="GET 제출">
    </form>

    <form action="" method="POST"> {% csrf_token %}
        <input type="text" name="var">
        <input type="submit" value="POST 제출">
    </form>
</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index Page</title>
</head>

<body>
    <h1>인덱스 화면</h1>
    <ul>
        <li><a href="{% url 'posts:post-list' %}">게시글 목록</a></li>
    </ul>
</body>

</html>

templates/posts/post_confirm_delete.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Post 삭제 화면</h1>
</body>

</html>

templates/posts/post_detail.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Post 상세 화면</h1>
</body>

</html>

templates/posts/post_form.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Post 입력 화면</h1>
</body>

</html>

templates/posts/post_list.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Post 목록 화면</h1>
</body>

</html>